apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VladyslavTokar/argocd.git
    targetRevision: main
    path: app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
